config/routes.rb
Rails.application.routes.draw do
  resources :user
  resources :telephone_number

  get 'user-telephones' => "telephone_number#user_numbers"
  get 'last-user' => 'user#last_user'

  root :to => "user#index"

end

app/models/telephone_number.rb
# == Schema Information
#
# Table name: telephone_numbers
#
#  id               :integer          not null, primary key
#  user_id          :integer
#  telephone_number :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
class TelephoneNumber < ActiveRecord::Base
  belongs_to :user
  validates :telephone_number, length: { in: 10..13 }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id            :integer          not null, primary key
#  email         :string           default(""), not null
#  name          :string           default(""), not null
#  address       :string
#  number        :string
#  neighbourhood :string
#  complement    :string
#  uf            :string
#  city          :string
#  country       :string
#  created_at    :datetime
#  updated_at    :datetime
#

class User < ActiveRecord::Base
  has_many :telephone_numbers
  validates :email, :name, :address, :number, :neighbourhood, :city, :country , :uf, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/telephone_number_controller.rb
class TelephoneNumberController < ApplicationController
  respond_to :html, :only => [:index]
  respond_to :json, :only => [:create]

  def index
    @telephones = TelephoneNumber.all
  end

  def create
    @tel = TelephoneNumber.create(telephone_params)

    respond_with @tel do |format|
      format.html {redirect_to root_path}
    end
  end

  def user_numbers
    @telephones = TelephoneNumber.where(user_id: params[:user_id].to_i)
    render json: @telephones.to_json
  end

  private

  def telephone_params
    params.require(:telephones).permit(:user_id, :telephone_number)
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  respond_to :html, :only => [:index]
  respond_to :json, :only => [:create, :update]

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)


    respond_with @user do |format|
      format.html {redirect_to root_path}
      if @user.save
        format.json { render json: @user.to_json, status: :created}
      else
        format.json { render json: @user.to_json, status: :unprocessable_entity}
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :address, :number, :neighbourhood, :city, :country, :uf)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/telephone_helper.rb
module TelephoneHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UserRegister</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/telephone/_telephone_form.html.erb
<%= form_tag(telephone_number_index_path, remote: true, type: "post", id: "telephone-form") do %>
  <%= hidden_field_tag :user_id,nil %>
  <%= text_field_tag :telephone_number, nil, placeholder: "numero de telefone" %>
  <%= submit_tag :cadastrar%>
<% end %>

<script charset="utf-8">
  $(document).ready(function(){
    telephoneForm = new $.userRegister.telephone_form_controller();
    telephoneForm.init();
  });
</script>

app/views/user/_user_form.html.erb
<%= form_tag('/user', remote: true, type: "post", id: "user-form") do %>
  <%= text_field_tag :email, nil, placeholder: "Email" %>
  <%= text_field_tag :name, nil, placeholder: "Nome" %>
  <%= text_field_tag :address, nil, placeholder: "Endereço" %>
  <%= text_field_tag :number, nil, placeholder: "Número" %>
  <%= text_field_tag :neighbourhood, nil, placeholder: "Bairro" %>
  <%= text_field_tag :complement, nil, placeholder: "Complemento" %>
  <%= text_field_tag :uf, nil, placeholder: "Estado" %>
  <%= text_field_tag :city, nil, placeholder: "Cidadae" %>
  <%= text_field_tag :country, nil, placeholder: "País" %>

  <%= submit_tag :cadastrar%>
<% end %>

<script charset="utf-8">
  $(document).ready(function(){
    userForm = new $.userRegister.user_form_controller();
    userForm.init();
  });
</script>

app/views/user/index.html.erb
<a href="#" id="add-new-user">Adcionar novo usuario </a>
<ul class="users-grid">
  <% @users.each do |user| %>
    <% if user.present? %>
      <li class="user-row" data-user="<%= user.id %>">
        <div class="user-name"> <%= user.email %> </div>
        <div class="user-name"> <%= user.name %> </div>
        <a href="#" class="user-links user-show-telephone">Exibit Números</a>
        <a href="#" class="user-links user-add-telephone">Adicionar novo númeto ao usuario</a>
      </li>
    <% end %>
  <% end %>
</ul>
<div id="forms">
  <div id="telephone-form-group" style="display:none;" class="form-group" >
    <div class="close">Fechar Formulário </div>
    <h5>Formulário de numero de telefone</h5>
    <%= render "telephone/telephone_form" %>
  </div>

  <div id="user-form-group" style="display:none;" class="form-group">
    <div class="close">Fechar Formulário </div>
    <h5>Adicionar Novo usuario</h5>
    <%= render "user_form" %>
  </div>

  <div id="user-number-group" style="display:none;" class="form-group">
    <div class="close">Fechar</div>
    <h5>Lista de números do usuario</h5>
    <ul id="number-list"></ul>
  </div>
</div>
<script charset="utf-8">
  $('.close').on('click', function(){
    $(this).parents('.form-group').hide();
  });
</script>